name       : mako
version    : 1.0.13
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/M/Mako/Mako-1.0.13.tar.gz : 95ee720cc3453063788515d55bd7ce4a2a77b7b209e4ac70ec5c86091eb02541
license    : MIT
component  : programming.python
summary    : Python templating language
description: |
    A super-fast templating language that borrows the best ideas from the existing templating languages.
builddeps  :
    - python-markupsafe
    - python-mock
    - python-pytest
rundeps    :
    - python-markupsafe
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
