name       : mako
version    : 1.0.4
release    : 2
source     :
    - https://pypi.python.org/packages/7a/ae/925434246ee90b42e8ef57d3b30a0ab7caf9a2de3e449b876c56dcb48155/Mako-1.0.4.tar.gz : fed99dbe4d0ddb27a33ee4910d8708aca9ef1fe854e668387a9ab9a90cbf9059
license    : MIT
component  : programming.python
summary    : Python templating language
description: |
    A super-fast templating language that borrows the best ideas from the existing templating languages.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
build      : |
    python setup.py build
    python3 setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
    python3 setup.py install --root=%installroot% --no-compile -O0
