name       : mako
version    : 1.0.14
release    : 7
source     :
    - https://files.pythonhosted.org/packages/1b/a5/023aba3d69aacef6bfc13797bdc3dd03c6fb4ae2dcd2fde7dffc37233924/Mako-1.0.14.tar.gz : f5a642d8c5699269ab62a68b296ff990767eb120f51e2e8f3d6afb16bdb57f4b
license    : MIT
component  : programming.python
summary    : Python templating language
description: |
    A super-fast templating language that borrows the best ideas from the existing templating languages.
builddeps  :
    - python-markupsafe
    - python-mock
    - python-pytest
rundeps    :
    - python-markupsafe
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
