name       : mako
version    : 1.0.10
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/M/Mako/Mako-1.0.10.tar.gz : 7165919e78e1feb68b4dbe829871ea9941398178fa58e6beedb9ba14acf63965
license    : MIT
component  : programming.python
summary    : Python templating language
description: |
    A super-fast templating language that borrows the best ideas from the existing templating languages.
builddeps  :
    - python-markupsafe
    - python-mock
    - python-pytest
rundeps    :
    - python-markupsafe
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
